# Generated by Django 5.2.7 on 2025-10-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url_to_image', models.URLField(blank=True, max_length=500, null=True)),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('general', 'General'), ('business', 'Business'), ('sports', 'Sports'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('science', 'Science')], max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api.newssource')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
