# Generated by Django 5.2.7 on 2025-10-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='source',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_name',
            field=models.CharField(default='Unknown Source', max_length=200),
        ),
        migrations.DeleteModel(
            name='NewsSource',
        ),
    ]
